Implements REST API /color/:color_id
chaintope/esplora-tapyrus pull request #18
Opened 2021-04-05 05:20 UTC by Yamaguchi

This PR implements 
- REST API /color/:color_id
- creating color_id based history(see doc/schema.md)
- calculating tx stats for colored coin

2021-04-05 06:52 UTC, azuchi requested changes

2021-04-05 06:52 UTC, azuchi commented on doc/API.md
>      "issuance_count": 2,
```suggestion
    "issued_tx_count": 2,
```

2021-04-05 06:52 UTC, azuchi commented on doc/API.md
>      "issuance_count": 0,
```suggestion
    "issued_tx_count": 0,
```

2021-04-05 06:52 UTC, azuchi commented on doc/API.md
>      "burn_count": 0,
```suggestion
    "burned_tx_count": 0,
```

2021-04-05 06:52 UTC, azuchi commented on doc/API.md
>      "burn_count": 1,
```suggestion
    "burned_tx_count": 1,
```

2021-04-05 06:52 UTC, azuchi commented on src/new_index/color.rs
> +    Transfering(TransferingInfo),
```suggestion
    Transferring(TransferringInfo),
```

2021-04-05 06:52 UTC, azuchi commented on src/new_index/color.rs
> +pub struct TransferingInfo {
```suggestion
pub struct TransferringInfo {
```

2021-04-05 06:52 UTC, azuchi commented on src/new_index/color.rs
> +// collect histories of issuring/burining colored coins in specified tx.
```suggestion
// collect histories of issuing/burning colored coins in specified tx.
```

2021-04-06 07:20 UTC, Yamaguchi commented on src/new_index/color.rs
> +// collect histories of issuring/burining colored coins in specified tx.
Fix typo (502a3c6d594f2c22c5d87353e04338163d2c2f6b)

2021-04-06 08:58 UTC, azuchi approved these changes

2021-04-06 08:58 UTC, merged