Implement new REST API: GET /colors/
chaintope/esplora-tapyrus pull request #33
Opened 2024-03-13 05:29 UTC by Yamaguchi

Implement new REST API

GET /colors/[:last_seen_color_id]

https://github.com/chaintope/tapyrus-explorer/issues/55

2024-03-15 04:41 UTC, Yamaguchi commented on Cargo.toml
> +rocksdb = { version = "^0.22.0", optional = true }
最新のmacOS環境でビルドが通らなかったため、アップデート

2024-03-15 04:42 UTC, Yamaguchi commented on src/new_index/db.rs
> +        let (key, value) = self.iter.next()?.ok()?;
最新のmacOS環境(rust: 1.76.0)でビルドが通らなかったため、修正

2024-03-15 04:55 UTC, Yamaguchi commented
ちなみに、この実装だとすでに運用中のesplora-tapyrusがある場合は、データを削除してインデックスを作り直す必要があります。テストネットの場合だとインデックスの再作成に、現状20分以上は必要です。

2024-03-15 05:28 UTC, azuchi commented on doc/API.md
> +Returns a list of the 25 `color_id`s
ここで返る25個のcolor_idはどういうソートがされて返ってきますか？

2024-03-15 05:28 UTC, azuchi commented on doc/API.md
> +if `last_seen_color_id` specified, returns a list of the next 25 `color_id`s after specified `last_seen_color_id`
`last_seen_color_id`より後に見つかったものを返すということですか？

2024-03-18 04:48 UTC, Yamaguchi commented on doc/API.md
> +if `last_seen_color_id` specified, returns a list of the next 25 `color_id`s after specified `last_seen_color_id`
そのとおりです。

2024-03-18 04:48 UTC, Yamaguchi commented on doc/API.md
> +Returns a list of the 25 `color_id`s
使用されたブロック高の降順で返すように変更しました。

2024-03-25 16:55 UTC, Yamaguchi commented
以下の2点を修正してまsう
- ブロック高をlittle endianで入れていたために高さ順にcolor_idを取得しようとした場合に正しく取れない現象を修正[3aa81f5](https://github.com/chaintope/esplora-tapyrus/pull/33/commits/3aa81f58796062afb3326f559c4b883c8f2c2329)
- GET /colors のレスポンスに発行量などの情報を追加で返すようにした[7c71bb8](https://github.com/chaintope/esplora-tapyrus/pull/33/commits/7c71bb8070f65665e37cfe801f2b6a806ee19c56)

2024-03-29 05:31 UTC, azuchi requested changes

2024-03-29 05:31 UTC, azuchi commented on doc/API.md
> +Returns a list of the 25 (`color_id`, `block_height`) pairs
他に、`chain_stats`と`mempool_stats`も含まれているようなので、それぞれ何を指すか説明を追記してください。

2024-03-31 19:21 UTC, Yamaguchi commented on doc/API.md
> +Returns a list of the 25 (`color_id`, `block_height`) pairs
[5b40145](https://github.com/chaintope/esplora-tapyrus/pull/33/commits/5b40145dade88edcece7f01023a274aef1a62bc6) 　で追記してます

2024-04-02 05:24 UTC, rantan approved these changes

2024-04-22 06:03 UTC, azuchi approved these changes

2024-04-22 06:03 UTC, merged